/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0fa4d57d-ed1c-4b3c-934a-8f0975db60fd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sTwmAxmS0",
    "aws_user_pools_web_client_id": "4qndo8t4o5pqg4tau8qudv0crq",
    "oauth": {}
};


export default awsmobile;
